name: Release

on:
    push:
        branches:
            - main
            - beta

jobs:
    release:
        permissions:
            id-token: write
            contents: write
            issues: write
            pull-requests: write

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - name: Release
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"
                  cache: "npm"
            - run: npm ci
            - run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
